# Generated by Django 5.0.1 on 2024-01-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member_name',
        ),
        migrations.AddField(
            model_name='team',
            name='twitter_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='whatsapp_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
